break_into_partial_movies: false
camera_resolutions:
  4k: 3840x2160
  default_resolution: portrait
  high: 1920x1080
  low: 854x480
  medium: 1280x720
  portrait: 1080x1920
directories:
  mirror_module_path: false
fps: 60
full_screen: false
style:
  background_color: '#000000'
  font: Consolas
  tex_template: default
universal_import_line: from manimlib import *
window_monitor: 1
window_position: UL
